### PR TITLE
162: Fix  is done to successfully  deploy fixed-asset go chaincode on test-network by  subarna patra

### PR DESCRIPTION
**Pull request by priyankaNagpalTest**

### CODE REVIEW

**Comment by priyankaNagpalTest** [comment]
Opening the PR on behalf of subarna as he was facing issue while raising the PR

**Comment by davidkel** [comment]
@priyankaNagpalTest Many thanks for the PR, could be please provide a DCO signoff. You can get details from 
https://github.com/hyperledger/caliper-benchmarks/pull/178/checks?check_run_id=5362923634

**Comment by priyankaNagpalTest** [comment]
Signed-off-by: Priyanka pnagpal1@in.ibm.com

**Comment by davidkel** [comment]
@priyankaNagpalTest Sorry the sign off has to be associated with the commit and can't be added as a comment to the PR, please see https://github.com/hyperledger/caliper-benchmarks/pull/178/checks?check_run_id=5362923634 for details about how to amend the commit and force push the change up.

**Review by davidkel — APPROVED** [review]
LGTM

**Pull request merged**
